{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "avatar-service.fullname" . }}-server
  labels:
    {{- include "avatar-service.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "avatar-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        {{- range .Values.networkPolicy.ingressNamespaces }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . | quote }}
        {{- end }}
      ports:
        - protocol: TCP
          port: http
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: metrics
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 5433
        - protocol: TCP
          port: 5672
        - protocol: TCP
          port: 9000
        - protocol: TCP
          port: 4317
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "avatar-service.fullname" . }}-worker
  labels:
    {{- include "avatar-service.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "avatar-service.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - protocol: TCP
          port: metrics
  egress:
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
      ports:
        - protocol: TCP
          port: 5433
        - protocol: TCP
          port: 5672
        - protocol: TCP
          port: 9000
        - protocol: TCP
          port: 4317
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
{{- end }}