// Code generated by MockGen. DO NOT EDIT.
// Source: internal/http/avatar_handler.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	domain "go-avatar-service/internal/domain"
	service "go-avatar-service/internal/service"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAvatarService is a mock of AvatarService interface.
type MockAvatarService struct {
	ctrl     *gomock.Controller
	recorder *MockAvatarServiceMockRecorder
}

// MockAvatarServiceMockRecorder is the mock recorder for MockAvatarService.
type MockAvatarServiceMockRecorder struct {
	mock *MockAvatarService
}

// NewMockAvatarService creates a new mock instance.
func NewMockAvatarService(ctrl *gomock.Controller) *MockAvatarService {
	mock := &MockAvatarService{ctrl: ctrl}
	mock.recorder = &MockAvatarServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAvatarService) EXPECT() *MockAvatarServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockAvatarService) Delete(ctx context.Context, id, userID string) (domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userID)
	ret0, _ := ret[0].(domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockAvatarServiceMockRecorder) Delete(ctx, id, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAvatarService)(nil).Delete), ctx, id, userID)
}

// GetByID mocks base method.
func (m *MockAvatarService) GetByID(ctx context.Context, id string) (domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAvatarServiceMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAvatarService)(nil).GetByID), ctx, id)
}

// GetContent mocks base method.
func (m *MockAvatarService) GetContent(ctx context.Context, id, size string) (service.AvatarContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetContent", ctx, id, size)
	ret0, _ := ret[0].(service.AvatarContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetContent indicates an expected call of GetContent.
func (mr *MockAvatarServiceMockRecorder) GetContent(ctx, id, size interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetContent", reflect.TypeOf((*MockAvatarService)(nil).GetContent), ctx, id, size)
}

// GetCurrentByUserID mocks base method.
func (m *MockAvatarService) GetCurrentByUserID(ctx context.Context, userID string) (domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentByUserID", ctx, userID)
	ret0, _ := ret[0].(domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentByUserID indicates an expected call of GetCurrentByUserID.
func (mr *MockAvatarServiceMockRecorder) GetCurrentByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentByUserID", reflect.TypeOf((*MockAvatarService)(nil).GetCurrentByUserID), ctx, userID)
}

// ListByUserID mocks base method.
func (m *MockAvatarService) ListByUserID(ctx context.Context, userID string) ([]domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByUserID", ctx, userID)
	ret0, _ := ret[0].([]domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByUserID indicates an expected call of ListByUserID.
func (mr *MockAvatarServiceMockRecorder) ListByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByUserID", reflect.TypeOf((*MockAvatarService)(nil).ListByUserID), ctx, userID)
}

// Upload mocks base method.
func (m *MockAvatarService) Upload(ctx context.Context, input service.UploadInput) (domain.Avatar, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, input)
	ret0, _ := ret[0].(domain.Avatar)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upload indicates an expected call of Upload.
func (mr *MockAvatarServiceMockRecorder) Upload(ctx, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockAvatarService)(nil).Upload), ctx, input)
}
